# Generated by Django 2.2.7 on 2019-12-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Turma', '0007_auto_20191217_2231'),
        ('Aluno', '0004_auto_20191216_2316'),
        ('Grupo', '0002_auto_20191217_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(help_text='Apenas num nome para identificação', max_length=200, verbose_name='Nome da atividade')),
                ('descricao_atividade', models.TextField(verbose_name='Descrição da Atividade')),
                ('data_atividade', models.DateField()),
                ('aluno_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aluno.Aluno')),
                ('grupo_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grupo.Grupo')),
                ('turma_pertencente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turma.Turma')),
            ],
        ),
    ]
