# Generated by Django 2.2.7 on 2020-01-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0001_initial'),
        ('Atividade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='evento_atribuido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Evento.Evento'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='aluno_atribuido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Aluno.Aluno'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='grupo_atribuido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Grupo.Grupo'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nome_atividade',
            field=models.CharField(help_text='Apenas um nome para identificação', max_length=200, verbose_name='Nome da atividade'),
        ),
    ]
