# Generated by Django 2.2.7 on 2019-12-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0003_auto_20191216_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(help_text='Nome para identificação do aluno', max_length=200, verbose_name='Nome do aluno'),
        ),
    ]
