# Generated by Django 2.2.7 on 2019-12-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(help_text='Use um nome significativo', max_length=100, unique=True, verbose_name='Nome do grupo')),
                ('data_criacao', models.DateField(default='2019-12-17')),
            ],
        ),
    ]
