# Generated by Django 2.2.7 on 2019-12-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='data_criacao',
            field=models.DateField(default='2019-12-18'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome_grupo',
            field=models.CharField(help_text='Use um nome significativo', max_length=100, verbose_name='Nome do grupo'),
        ),
    ]
