# Generated by Django 2.2.7 on 2019-12-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_criacao',
            field=models.DateField(default='06-12-2019'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome_turma',
            field=models.CharField(help_text='Use um nome significativo', max_length=100, unique=True, verbose_name='Nome da turma'),
        ),
    ]
