# Generated by Django 2.2.7 on 2019-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turma', '0002_auto_20191206_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_criacao',
            field=models.DateField(default='2019-12-06'),
        ),
    ]
