# Generated by Django 2.2.7 on 2019-12-07 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turma', '0003_auto_20191206_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_criacao',
            field=models.DateField(default='2019-12-07'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(help_text='Nome para identificação do aluno', max_length=200, verbose_name='Nome do aluno')),
                ('turma_pertencente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turma.Turma')),
            ],
        ),
    ]
