# Generated by Django 2.2.7 on 2019-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turma', '0004_auto_20191206_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_criacao',
            field=models.DateField(default='2019-12-08'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
