# Generated by Django 2.2.7 on 2019-12-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turma', '0005_auto_20191208_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_criacao',
            field=models.DateField(default='2019-12-17'),
        ),
    ]
