# Generated by Django 2.2.7 on 2020-01-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turma', '0007_auto_20191217_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_criacao',
            field=models.DateField(default='2020-01-15'),
        ),
    ]
