# Generated by Django 2.2.7 on 2020-01-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Turma', '0008_auto_20200115_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=200)),
                ('descricao_evento', models.TextField()),
                ('quantidade_atividades', models.IntegerField()),
                ('turma_pertencente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turma.Turma')),
            ],
        ),
    ]
